node {
    stage('Checkout SCM') {
        checkout scm
    }

    stage('Build') {
        docker.image('python:2-alpine').inside {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }

    stage('Test') {
        docker.image('qnib/pytest').inside {
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            junit 'test-reports/results.xml'
        }
    }

    stage('Manual Approval') {
        input message: 'Lanjutkan ke tahap Deploy?'
    }

    stage('Deploy') {
        stage('Build Docker Image') {
            sh 'docker build -t add2vals-python-app:latest .'
            sh 'docker save -o add2vals-python-app.tar add2vals-python-app:latest'
        }

        stage('Deploy to EC2 App Server') {
            withCredentials([sshUserPrivateKey(credentialsId: 'Add2Val-Instance-Key', keyFileVariable: 'SSH_KEY')]) {
                sh '''
                    scp -o StrictHostKeyChecking=no -i $SSH_KEY add2vals-python-app.tar ec2-user@52.77.247.20:/tmp
                    ssh -i $SSH_KEY ec2-user@52.77.247.20 << EOF
                    sudo docker load < /tmp/add2vals-python-app.tar
                    sudo docker run -d --name add2vals-python-app -p 8080:8080 add2vals-python-app:latest
                    EOF
                '''
            }
        }

        stage('Wait After Deployment Success') {
            sh 'sleep 60'
        }
    }
}
